export const fontFamilyList = [
    "Inter Regular",
    "Inter Bold", 
    "Inter Extra Bold", 
    "Inter Extra Light", 
    "Inter Light", 
    "Inter Medium", 
    "Inter SemiBold", 
    "Inter Thin", 
    "Brush Script MT",
    "Impact",
    "Arial Black",
    "Amatic SC Regular",
    "Amatic SC Bold",
    "Cinzel Regular",
    "Cinzel Medium",
    "Cinzel Bold",
    "Cinzel SemiBold",
    "Cinzel ExtraBold",
    "Barrio Regular",
    "Bungee Outline Regular",
    "Bungee Shade Regular",
    "Comfortaa Regular",
    "Comfortaa Medium",
    "Comfortaa Light",
    "Comfortaa Bold",
    "Comfortaa SemiBold", 
    "Dancing Script Bold", 
    "Dancing Script Regular", 
    "DMSerif Display Italic", 
    "DMSerif Display Regular", 
    "FrederickatheGreat Regular", 
    "GreatVibes Regular", 
    "HennyPenny Regular", 
    "IndieFlower Regular", 
    "JosefinSans Bold", 
    "JosefinSans Bold Italic", 
    "JosefinSans Extra Light", 
    "JosefinSans Extra Light Italic", 
    "JosefinSans Italic", 
    "JosefinSans Light", 
    "JosefinSans Light Italic", 
    "JosefinSans Medium", 
    "JosefinSans Medium Italic", 
    "JosefinSans Regular", 
    "JosefinSans SemiBold", 
    "JosefinSans SemiBold Italic", 
    "JosefinSans Thin", 
    "JosefinSans Thin Italic", 
    "LibreFranklin Bold", 
    "LibreFranklin Bold Italic", 
    "LibreFranklin Extra Light", 
    "LibreFranklin ExtraLight Italic", 
    "LibreFranklin Italic", 
    "LibreFranklin Light", 
    "LibreFranklin Light Italic", 
    "LibreFranklin Medium", 
    "LibreFranklin Medium Italic", 
    "LibreFranklin Semi Bold", 
    "LibreFranklin Semi Bold Italic", 
    "LibreFranklin Thin", 
    "LibreFranklin Thin Italic", 
    "Lobster Regular", 
    "Londrina Outline Regular", 
    "Monoton Regular", 
    "Montserrat Black", 
    "Montserrat Black Italic", 
    "Montserrat Bold", 
    "Montserrat Bold Italic", 
    "Montserrat Extra Bold", 
    "Montserrat Extra Bold Italic", 
    "Montserrat Extra Light", 
    "Montserrat Extra Light Italic", 
    "Montserrat Italic", 
    "Montserrat Light", 
    "Montserrat Light Italic", 
    "Montserrat Medium", 
    "Montserrat Medium Italic", 
    "Montserrat Regular", 
    "Montserrat Semi Bold", 
    "Montserrat Semi Bold Italic", 
    "Montserrat Thin", 
    "Montserrat Thin Italic", 
    "NoeDisplay Bold", 
    "OpenSans Bold", 
    "OpenSans Bold Italic", 
    "OpenSans Extra Bold", 
    "OpenSans Extra Bold Italic", 
    "OpenSans Italic", 
    "OpenSans Light", 
    "OpenSans Light Italic", 
    "OpenSans Medium", 
    "OpenSans Medium Italic", 
    "OpenSans Regular", 
    "OpenSans Semi Bold", 
    "OpenSans Semi Bold Italic", 
    "Permanent Marker Regular", 
    "Pirata One Regular", 
    "Playfair Display Black", 
    "Playfair Display Black Italic", 
    "Playfair Display Bold", 
    "Playfair Display Bold Italic", 
    "Playfair Display Extra Bold", 
    "Playfair Display Extra Bold Italic", 
    "Playfair Display Italic", 
    "Playfair Display Medium", 
    "Playfair Display Medium Italic", 
    "Playfair Display Regular", 
    "Playfair Display Semi Bold", 
    "Playfair Display Semi Bold Italic", 
    "Prata Regular", 
    "Press Start 2P Regular", 
    // "Raleway Black", 
    // "Raleway Black Italic", 
    // "Raleway Bold", 
    // "Raleway Bold Italic",
    // "Raleway Extra Bold", 
    // "Raleway Extra Bold Italic", 
    // "Raleway Extra Light", 
    // "Raleway Extra Light Italic", 
    // "Raleway Italic", 
    // "Raleway Light", 
    // "Raleway Light Italic", 
    // "Raleway Medium", 
    // "Raleway Regular", 
    // "Raleway Semi Bold", 
    // "Raleway Semi Bold Italic", 
    // "Raleway Thin", 
    // "Raleway Thin Italic", 
    "Rampart One Regular", 
    "Roboto Black", 
    "Roboto Black Italic", 
    "Roboto Bold", 
    "Roboto Bold Italic", 
    "Roboto Italic", 
    "Roboto Light", 
    "Roboto Light Italic", 
    "Roboto Medium", 
    "Roboto Medium Italic", 
    "Roboto Regular", 
    "Roboto Thin", 
    "Roboto Thin Italic", 
    "RockSalt Regular", 
    "ShadowsInto Light Regular", 
    "SpaceGrotesk Bold", 
    "SpaceGrotesk Light", 
    "SpaceGrotesk Medium", 
    "SpaceGrotesk Regular", 
    "SpaceGrotesk SemiBold", 
    "VastShadow Regular", 
    

    
]